# Example usage of paw_ansible_role_mysql

# Simple include with default parameters
include paw_ansible_role_mysql

# Or with custom parameters:
# class { 'paw_ansible_role_mysql':
#   mysql_port => '3306',
#   mysql_socket => undef,
#   mysql_bind_address => '0.0.0.0',
#   mysql_datadir => '/var/lib/mysql',
#   mysql_pid_file => undef,
#   mysql_sql_mode => undef,
#   mysql_syslog_tag => undef,
#   mysql_log => undef,
#   mysql_log_error => undef,
#   mysql_slow_query_log_file => undef,
#   mysql_slow_query_time => '2',
#   mysql_server_id => '1',
#   mysql_expire_logs_days => '10',
#   mysql_max_binlog_size => '100M',
#   mysql_binlog_format => 'ROW',
#   mysql_key_buffer_size => '256M',
#   mysql_max_allowed_packet => '64M',
#   mysql_table_open_cache => '256',
#   mysql_sort_buffer_size => '1M',
#   mysql_read_buffer_size => '1M',
#   mysql_read_rnd_buffer_size => '4M',
#   mysql_myisam_sort_buffer_size => '64M',
#   mysql_thread_cache_size => '8',
#   mysql_query_cache_type => '0',
#   mysql_query_cache_size => '16M',
#   mysql_query_cache_limit => '1M',
#   mysql_max_connections => '151',
#   mysql_tmp_table_size => '16M',
#   mysql_max_heap_table_size => '16M',
#   mysql_group_concat_max_len => '1024',
#   mysql_join_buffer_size => '262144',
#   mysql_wait_timeout => '28800',
#   mysql_lower_case_table_names => '0',
#   mysql_event_scheduler_state => 'OFF',
#   mysql_innodb_large_prefix => '1',
#   mysql_innodb_file_format => 'barracuda',
#   mysql_innodb_file_per_table => '1',
#   mysql_innodb_buffer_pool_size => '256M',
#   mysql_innodb_log_file_size => '64M',
#   mysql_innodb_log_buffer_size => '8M',
#   mysql_innodb_flush_log_at_trx_commit => '1',
#   mysql_innodb_lock_wait_timeout => '50',
#   mysql_mysqldump_max_allowed_packet => '64M',
#   mysql_config_include_dir => undef,
#   mysql_root_username => 'root',
#   mysql_root_password => 'root',
#   mysql_user_name => 'root',
#   mysql_user_password => 'root',
#   mysql_user_home => '/root',
#   mysql_root_home => '/root',
#   mysql_root_password_update => false,
#   mysql_user_password_update => false,
#   mysql_enabled_on_startup => true,
#   overwrite_global_mycnf => true,
#   mysql_copy_root_user_mycnf => true,
#   mysql_enablerepo => undef,
#   mysql_python_package_debian => 'python3-mysqldb',
#   mysql_skip_name_resolve => false,
#   mysql_log_file_group => 'mysql',
#   mysql_slow_query_log_enabled => false,
#   mysql_config_include_files => [],
#   mysql_databases => [],
#   mysql_users => [],
#   mysql_disable_log_bin => false,
#   mysql_replication_role => undef,
#   mysql_replication_master => undef,
#   mysql_replication_master_inventory_host => '{{ mysql_replication_master }}',
#   mysql_replication_user => [],
#   mysql_hide_passwords => false,
# }
